FROM adoptopenjdk/maven-openjdk12-openj9

COPY ./project /project
WORKDIR /project/

RUN mkdir -p /mvn/repository
RUN mvn -Dmaven.repo.local=/mvn/repository install liberty:create-server dependency:go-offline -DskipTests

WORKDIR /project/user-app

ENV APPSODY_MOUNTS="src:/project/user-app/src;pom.xml:/project/user-app/pom.xml" \
    APPSODY_DEPS=/mvn/repository \
    \
    APPSODY_INSTALL="echo install" \
    \
    APPSODY_RUN="mvn -Dmaven.repo.local=/mvn/repository liberty:dev" \
    APPSODY_RUN_KILL=false \
    \
    APPSODY_DEBUG="mvn -Dmaven.repo.local=/mvn/repository liberty:dev -DhotTests=true" \
    APPSODY_DEBUG_KILL=false \
    \
    APPSODY_TEST="mvn -Dmaven.repo.local=/mvn/repository verify" \
    APPSODY_TEST_KILL=false \
    \
    PORT=9080

EXPOSE 9080 9443 7777
